# Generated by Django 3.1.7 on 2021-02-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='friendy_name',
            new_name='friendly_name',
        ),
    ]
